### ISSUE TITLE
Fix Command Injection Vulnerability

### ISSUE THREAD

**Issue by lattera** [misterpeguero/misc#1]
[This](https://github.com/misterpeguero/misc/blob/9b7e714ebdfc9e4f5bb26039a1bab5b3aa354fcf/script/snapshotting/snapshot.py#L198) is vulnerable to command injection.

The first example in this piece of Python documentation shows how to securely call shell applications:
* https://docs.python.org/2/library/subprocess.html

Example:
`subprocess.call(["ls", "-l"])`

Note the use of arrays and separate array indexes for each argument. You are using piping to separate commands. You might want to consider bundling a companion script that executes the commands and does the piping for you. Otherwise, doing all the piping in python is going to be messy.

**Comment by RobotsOnDrugs** [comment]
Perhaps this is a better link: https://docs.python.org/3/library/subprocess.html#replacing-shell-pipeline
The script is Python 3, fortunately.

**Comment by misterpeguero** [comment]
@lattera Thank you for reporting this vulnerability! Please advise that I am a relatively new to Python development and was entirely unaware of this particular issue beforehand. I will absolutely do my best to ensure this vulnerability is taken care of within a reasonable amount of time.

@RobotsOnDrugs Thank you for the convenient link! Please see my message above for further details in regards to this vulnerability.

**Comment by misterpeguero** [comment]
As developing a solution to dynamically pipe a series of lists will take a considerable amount of time, until such a solution is implemented and the vulnerability is patched, I have decided to discontinue hosting the ZFS snapshot management script from the misc repository. This issue will remain closed. Thank you for understanding.
